version: '3.8'
services:
  www:
    image: php:8.1.1-apache
    volumes:
      - ./html:/var/www/html/
    ports:
      - 80:80
      - 443:443
    networks:
      - php-dev
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: developer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - php-dev
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - php-dev
    depends_on:
      - db
networks:
  php-dev:
    driver: bridge
  